version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'daily'
      assignees:
          - 'mmattbtw'
      commit-message:
          prefix: 'chore(deps): '
